### ISSUE TITLE
python pymm_run.py restore step: Use of SCRAM-SHA-256 requires undigested passwords

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#10]
My pymongo is 2.9.1 (as  in the requirements.txt)

I ran these two successfully as far as I can tell:
```
$ docker run --name match-mongo -d -p 27017:27017 mongo mongod --smallfiles --replSet=rs0
$ docker exec -it match-mongo mongo matchminer --eval "rs.initiate();"
```
Now:
`$ python2.7 pymm_run.py restore`
```
[INFO] settings: DEV
[INFO] settings: mongodb://localhost:27017/matchminer?replicaSet=rs0
/Users/ipozdnya/matchminer-api/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments of rule 'consented'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/Users/ipozdnya/matchminer-api/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments of rule 'match'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/Users/ipozdnya/matchminer-api/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments of rule 'normalized'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/Users/ipozdnya/matchminer-api/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments of rule 'unique'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
[INFO] settings: DEV
[INFO] settings: mongodb://localhost:27017/matchminer?replicaSet=rs0
[INFO] mongorestore --host rs0/localhost:27017 --db matchminer --drop /Users/ipozdnya/matchminer-api/data/matchminer
2019-02-21T11:46:41.458+0100	building a list of collections to restore from /Users/ipozdnya/matchminer-api/data/matchminer dir
2019-02-21T11:46:41.465+0100	reading metadata file from /Users/ipozdnya/matchminer-api/data/matchminer/genomic.metadata.json
2019-02-21T11:46:41.465+0100	restoring matchminer.genomic from file /Users/ipozdnya/matchminer-api/data/matchminer/genomic.bson
2019-02-21T11:46:41.468+0100	reading metadata file from /Users/ipozdnya/matchminer-api/data/matchminer/clinical.metadata.json
2019-02-21T11:46:41.468+0100	restoring matchminer.clinical from file /Users/ipozdnya/matchminer-api/data/matchminer/clinical.bson
2019-02-21T11:46:41.532+0100	restoring indexes for collection matchminer.clinical from metadata
2019-02-21T11:46:41.534+0100	finished restoring matchminer.clinical (92 documents)
2019-02-21T11:46:44.459+0100	[#####################...]  matchminer.genomic  77.1 MB/84.8 MB  (91.0%)
2019-02-21T11:46:45.128+0100	restoring indexes for collection matchminer.genomic from metadata
2019-02-21T11:46:45.129+0100	finished restoring matchminer.genomic (87980 documents)
2019-02-21T11:46:45.129+0100	done
Traceback (most recent call last):
  File "pymm_run.py", line 467, in <module>
    args.func(args)
  File "pymm_run.py", line 186, in bootstrap_restore
    db = get_db()
  File "/Users/ipozdnya/matchminer-api/matchminer/database.py", line 50, in get_db
    connection[MONGO_DBNAME].add_user(MONGO_USERNAME, MONGO_PASSWORD)
  File "/Users/ipozdnya/miniconda3/envs/matchminer/lib/python2.7/site-packages/pymongo/database.py", line 966, in add_user
    (not uinfo["users"]), name, password, read_only, **kwargs)
  File "/Users/ipozdnya/miniconda3/envs/matchminer/lib/python2.7/site-packages/pymongo/database.py", line 892, in _create_or_update_user
    read_preference=ReadPreference.PRIMARY, **opts)
  File "/Users/ipozdnya/miniconda3/envs/matchminer/lib/python2.7/site-packages/pymongo/database.py", line 535, in command
    codec_options, **kwargs)[0]
  File "/Users/ipozdnya/miniconda3/envs/matchminer/lib/python2.7/site-packages/pymongo/database.py", line 440, in _command
    msg, allowable_errors)
  File "/Users/ipozdnya/miniconda3/envs/matchminer/lib/python2.7/site-packages/pymongo/helpers.py", line 213, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command SON([('createUser', 'user'), ('pwd', u'<some encoded password here>'), ('digestPassword', False), ('roles', ['dbOwner']), ('writeConcern', {})]) on namespace matchminer.$cmd failed: Use of SCRAM-SHA-256 requires undigested passwords
```

That happened to me before when on another machine and then I fixed it by getting into mongo and creating an admin user:

```
> use admin
> db.createUser({     user:"admin",     pwd:"abc123",     roles:[{role:"userAdminAnyDatabase",db:"admin"}],     passwordDigestor:"server" })
```
This time it did not help. Dropping and re-creating that user did not help either. 

Running `$ nosetests tests` results in the same error.

Please suggest a workaround. Thanks!

**Comment by ethansiegl** [comment]
hmm are you able to load any data into the database using a mongorestore command manually? would have to look something like this: 

`mongorestore -d matchminer --drop --dir=./data/backup`

note - this command will drop your clinical and genomic collections in your local db if you have any data in them

**Comment by cegg** [comment]
I think that mongorestore load worked.

```
$ mongorestore -d matchminer --drop --dir=./data/backup
2019-03-12T10:14:46.476+0100	building a list of collections to restore from ./data/backup dir
2019-03-12T10:14:46.487+0100	restoring matchminer.clinical from file data/backup/clinical.bson
2019-03-12T10:14:46.494+0100	restoring matchminer.genomic from file data/backup/genomic.bson
2019-03-12T10:14:46.936+0100	no indexes to restore
2019-03-12T10:14:46.936+0100	finished restoring matchminer.clinical (92 documents)
2019-03-12T10:14:49.477+0100	[#####...................]  matchminer.genomic  19.5 MB/84.8 MB  (23.0%)
2019-03-12T10:14:52.477+0100	[##########..............]  matchminer.genomic  38.8 MB/84.8 MB  (45.7%)
2019-03-12T10:14:55.481+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:14:58.478+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:01.477+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:04.480+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:07.479+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:10.476+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:13.477+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:16.476+0100	[#############...........]  matchminer.genomic  48.4 MB/84.8 MB  (57.1%)
2019-03-12T10:15:19.476+0100	[###############.........]  matchminer.genomic  54.4 MB/84.8 MB  (64.2%)
2019-03-12T10:15:22.477+0100	[################........]  matchminer.genomic  58.0 MB/84.8 MB  (68.4%)
2019-03-12T10:15:25.476+0100	[################........]  matchminer.genomic  58.0 MB/84.8 MB  (68.4%)
2019-03-12T10:15:28.476+0100	[###################.....]  matchminer.genomic  67.5 MB/84.8 MB  (79.7%)
2019-03-12T10:15:31.476+0100	[###################.....]  matchminer.genomic  67.5 MB/84.8 MB  (79.7%)
2019-03-12T10:15:34.476+0100	[###################.....]  matchminer.genomic  67.5 MB/84.8 MB  (79.7%)
2019-03-12T10:15:37.477+0100	[#####################...]  matchminer.genomic  77.1 MB/84.8 MB  (91.0%)
2019-03-12T10:15:40.476+0100	[#####################...]  matchminer.genomic  77.1 MB/84.8 MB  (91.0%)
2019-03-12T10:15:43.479+0100	[#####################...]  matchminer.genomic  77.1 MB/84.8 MB  (91.0%)
2019-03-12T10:15:46.479+0100	[#####################...]  matchminer.genomic  77.1 MB/84.8 MB  (91.0%)
2019-03-12T10:15:48.978+0100	no indexes to restore
2019-03-12T10:15:48.978+0100	finished restoring matchminer.genomic (87980 documents)
2019-03-12T10:15:48.978+0100	done

```
When I get in the container and check mongo content I get:
```
rs0:PRIMARY> use matchminer
switched to db matchminer
rs0:PRIMARY> show collections
clinical
genomic
storage
rs0:PRIMARY> db.clinical.count()
92
rs0:PRIMARY> db.genomic.count()
87980
rs0:PRIMARY> db.storage.count()
1
rs0:PRIMARY> db.storage.find()
{ "_id" : ObjectId("5c87787577fb5cac8000c26c"), "storage" : { "engine" : "wiredTiger", "options" : { "directoryPerDB" : false, "directoryForIndexes" : false, "groupCollections" : false } } }
```

Is that the expected state?

**Comment by ethansiegl** [comment]
yup the counts look correct. going to close this issue as it seems to be resolved
