### ISSUE TITLE
Setup failed during elasticsearch initializaiton: No route to host

### ISSUE THREAD

**Issue by djhshih** [dfci/matchminer-api#32]
I followed the setup instructions, but it didn't work out of the box:

```
$ git clone git@github.com:dfci/matchminer-api.git
$ cd matchminer-api
$ ./setup.sh
```

I ran into and resolved two errors:
1. An error due to the `mongo` executable not being shipped with the `mm-mongo` container (`mongo` image). So, I replaced it with `mongosh`.
2. An error due to `numpy 1.23.3` not being available when the `mm-api` container tried to run `pip install -r requirements.txt`.

Resolved these with
```
--- a/requirements.txt
+++ b/requirements.txt
@@ -91,7 +91,8 @@ nose==1.3.7
     # via
     #   -r requirements.in
     #   oncotreenx
-numpy==1.23.3
+numpy==1.21.6
    # via pandas
 oauth2client==2.0.2
     # via -r requirements.in


--- a/setup.sh
+++ b/setup.sh
@@ -24,7 +24,7 @@ echo "*****************"
 sleep 5

 echo "Add dev user to database to bypass authentication"
-docker-compose exec mm-mongo mongo matchminer --eval 'db.user.replaceOne({
+docker-compose exec mm-mongo mongosh matchminer --eval 'db.user.replaceOne({
 ```

But now,

```
$ ./setup
...
Using Mongosh:          1.6.1
...
 ⠿ Container mm-elastic  Started                                                                [382/530]
[WARNING] settings:
[WARNING] settings: mongodb://mm-mongo:27017/matchminer
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'consented'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'match'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'normalized'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'unique'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'consented'
  "'%s'" % method_name.split('_', 2)[-1])
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'match'
  "'%s'" % method_name.split('_', 2)[-1])
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'normalized'
  "'%s'" % method_name.split('_', 2)[-1])
[WARNING] NO AUTHENTICATION IS ENABLED - SKIPPING HIPAA LOGGING
[WARNING] settings:
[WARNING] settings: mongodb://mm-mongo:27017/matchminer
/usr/local/lib/python3.7/site-packages/eve/flaskapp.py:310: UserWarning: XML setting is deprecated and wi
ll be removed in future release. Please use RENDERERS instead.
  warnings.warn(msg.format("XML"))
[INFO] reset_elasticsearch
[INFO] http://mm-elastic:9200/matchminer
[INFO]
[INFO]
[INFO] delete_elasticsearch_index
[WARNING] DELETE http://mm-elastic:9200/matchminer [status:N/A request:3.052s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host
```

Any suggestions?

Additionally, what version of `mongo` was docker-compose supposed to retrieve?
`docker-compose.yml` did not specify a version number, and the current matchminer-api setup is apparently not compatible with the latest version of mongo, because it relies on the deprecated `mongo` executable rather than `mongosh`.

```
$ uname -a
Linux durus 6.1.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Sat, 07 Jan 2023 15:10:07 +0000 x86_64 GNU/Linux
```

```
$ docker version
Client:
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.19.4
 Git commit:        3a2c30b63a
 Built:             Tue Dec 20 20:43:40 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.4
  Git commit:       42c8b31499
  Built:            Tue Dec 20 20:42:46 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323.m
 runc:
  Version:          1.1.4
  GitCommit:
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

```
$ docker-compose version
Docker Compose version 2.14.2
```

**Comment by djhshih** [comment]
I tried several `mongo` docker images built 3 months ago (which is roughly as old as this repo). None of them worked.

Containers from mongo images older than 6.0 silently disappear immediately, and they cease to be running immediately after starting:
```
$ docker-compose up -d mm-mongo mm-elastic
[+] Running 2/2
 ⠿ Container mm-elastic  Started                                                                    0.5s
 ⠿ Container mm-mongo    Started                                                                    0.5s

$ docker-compose ps
NAME                IMAGE               COMMAND             SERVICE             CREATED             STATUS              PORTS
```

Container from mongo:6.0.2-focal gives do not come with the `mongo` executable:

```
$ docker-compose exec mm-mongo mongo matchminer --eval 'db.user.replaceOne({
> ...
OCI runtime exec failed: exec failed: unable to start container process: exec: "mongo": executable file not found in $PATH: unknown
```

Configuration
```
diff --git a/docker-compose.yml b/docker-compose.yml
index d1598fc..ac08b57 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -25,7 +25,10 @@ services:
   mm-mongo:
     container_name: mm-mongo
     restart: "no"
-    image: mongo
+    image: "mongo:6.0.2-focal"
+#   image: "mongo:5.0.13-focal"
+#   image: "mongo:4.4.17-focal"
+#   image: "mongo:4.0.28-xenial"
     ports:
       - "27017:27017"
     networks:
```

**Comment by djhshih** [comment]
For containers from mong:6.0.2-focal and later, I can get further in the setup script by replacing `mongo` with `mongosh` as above, but I am getting the following error:

```
$ docker-compose run --rm mm-api python pymm_run.py reset-elasticsearch
[+] Running 2/0
 ⠿ Container mm-mongo    Running                                                                    0.0s
 ⠿ Container mm-elastic  Created                                                                    0.0s
[+] Running 1/1
 ⠿ Container mm-elastic  Started                                                                    0.2s
[WARNING] settings:
[WARNING] settings: mongodb://mm-mongo:27017/matchminer
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'consented'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'match'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'normalized'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
...
[WARNING] settings: mongodb://mm-mongo:27017/matchminer                                          [29/963]
/usr/local/lib/python3.7/site-packages/eve/flaskapp.py:310: UserWarning: XML setting is deprecated and wi
ll be removed in future release. Please use RENDERERS instead.
  warnings.warn(msg.format("XML"))
[INFO] reset_elasticsearch
[INFO] http://mm-elastic:9200/matchminer
[INFO]
[INFO]
[INFO] delete_elasticsearch_index
[WARNING] DELETE http://mm-elastic:9200/matchminer [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by djhshih** [comment]
I see that the `dfci/matchminer` repo's `setup.sh` uses the `mongo:6.0-focal` image, so that is what I am using now, but I am still getting the Connection refused error during `setup.sh`.

```
$ docker-compose run --rm mm-api python pymm_run.py reset-elasticsearch
...
[+] Running 1/1                                                                                 [226/360]
 ⠿ Container mm-elastic  Started                                                                    0.2s
[WARNING] settings:
[WARNING] settings: mongodb://mm-mongo:27017/matchminer
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'consented'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'match'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'normalized'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/matchminerAPI/cerberus1/cerberus.py:1272: UserWarning: No validation schema is defined for the arguments
 of rule 'unique'
  "'%s'" % '_'.join(method_name.split('_')[2:]))
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'consented'
  "'%s'" % method_name.split('_', 2)[-1])
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'match'
  "'%s'" % method_name.split('_', 2)[-1])
/usr/local/lib/python3.7/site-packages/cerberus/validator.py:1402: UserWarning: No validation schema is d
efined for the arguments of rule 'normalized'
  "'%s'" % method_name.split('_', 2)[-1])
[WARNING] NO AUTHENTICATION IS ENABLED - SKIPPING HIPAA LOGGING
[WARNING] settings:
[WARNING] settings: mongodb://mm-mongo:27017/matchminer
/usr/local/lib/python3.7/site-packages/eve/flaskapp.py:310: UserWarning: XML setting is deprecated and wi
ll be removed in future release. Please use RENDERERS instead.
  warnings.warn(msg.format("XML"))
[INFO] reset_elasticsearch
[INFO] http://mm-elastic:9200/matchminer
[INFO]
[INFO]
[INFO] delete_elasticsearch_index
[WARNING] DELETE http://mm-elastic:9200/matchminer [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by djhshih** [comment]
The cause of the above error appears to be that `mm-elastic` could not be launched successfully in `setup.sh`

$ docker-compose up mm-elastic

Attaching to mm-elastic
mm-elastic  | [2023-01-21T10:32:49,842][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [unknown] uncaught exception in thread [main]
mm-elastic  | org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to create node environment
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:163) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | Caused by: java.lang.IllegalStateException: Failed to create node environment
mm-elastic  | 	at org.elasticsearch.node.Node.<init>(Node.java:299) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	... 6 more
mm-elastic  | Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
mm-elastic  | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:90) ~[?:?]
mm-elastic  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111) ~[?:?]
mm-elastic  | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116) ~[?:?]
mm-elastic  | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:389) ~[?:?]
mm-elastic  | 	at java.nio.file.Files.createDirectory(Files.java:694) ~[?:?]
mm-elastic  | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:801) ~[?:?]
mm-elastic  | 	at java.nio.file.Files.createDirectories(Files.java:787) ~[?:?]
mm-elastic  | 	at org.elasticsearch.env.NodeEnvironment.lambda$new$0(NodeEnvironment.java:273) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.env.NodeEnvironment$NodeLock.<init>(NodeEnvironment.java:206) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:270) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.node.Node.<init>(Node.java:296) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.node.Node.<init>(Node.java:266) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:212) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) ~[elasticsearch-6.8.12.jar:6.8.12]
mm-elastic  | 	... 6 more
mm-elastic exited with code 1

**Comment by djhshih** [comment]
On that note, is it really necessary to have 
```
docker-compose build mm-api
``
executed twice in `setup.sh`? The outputs seem to be the same after each of them.

**Comment by djhshih** [comment]
The `mm-elastic` start up error appears to be due to the fact that root:root owns many of the directories in this repo after initial attempts to start `mm-elastic` when docker-compose is run (without sudo).

After fixing the ownership of those directories... I get:

```
$ docker-compose up mm-elastic
Attaching to mm-elastic
mm-elastic  | [2023-01-21T10:45:03,359][INFO ][o.e.e.NodeEnvironment    ] [JplwvI5] using [1] data paths, mounts [[/usr/share/elasticsearch/data (/dev/sdb1)]], net usable_space [699.3gb], net total_space [1.8tb], types [ext4]
mm-elastic  | [2023-01-21T10:45:03,360][INFO ][o.e.e.NodeEnvironment    ] [JplwvI5] heap size [1gb], compressed ordinary object pointers [true]
mm-elastic  | [2023-01-21T10:45:03,361][INFO ][o.e.n.Node               ] [JplwvI5] node name derived from node ID [JplwvI5gTYi7E24MAkUSfw]; set [node.name] to override
mm-elastic  | [2023-01-21T10:45:03,361][INFO ][o.e.n.Node               ] [JplwvI5] version[6.8.12], pid[1], build[default/docker/7a15d2a/2020-08-12T07:27:20.804867Z], OS[Linux/6.1.4-arch1-1/amd64], JVM[AdoptOpenJDK/OpenJDK 64-Bit Server VM/14.0.1/14.0.1+7]
mm-elastic  | [2023-01-21T10:45:03,361][INFO ][o.e.n.Node               ] [JplwvI5] JVM arguments [-Xms1g, -Xmx1g, -XX:+UseG1GC, -XX:G1ReservePercent=25, -XX:InitiatingHeapOccupancyPercent=30, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -XX:+ShowCodeDetailsInExceptionMessages, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch-3725008302545195239, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Djava.locale.providers=COMPAT, -XX:UseAVX=2, -Des.cgroups.hierarchy.override=/, -Des.path.home=/usr/share/elasticsearch, -Des.path.conf=/usr/share/elasticsearch/config, -Des.distribution.flavor=default, -Des.distribution.type=docker]
mm-elastic  | [2023-01-21T10:45:03,935][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [aggs-matrix-stats]
mm-elastic  | [2023-01-21T10:45:03,935][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [analysis-common]
mm-elastic  | [2023-01-21T10:45:03,935][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [ingest-common]
mm-elastic  | [2023-01-21T10:45:03,935][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [ingest-geoip]
mm-elastic  | [2023-01-21T10:45:03,935][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [ingest-user-agent]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [lang-expression]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [lang-mustache]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [lang-painless]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [mapper-extras]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [parent-join]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [percolator]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [rank-eval]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [reindex]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [repository-url]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [transport-netty4]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [tribe]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-ccr]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-core]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-deprecation]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-graph]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-ilm]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-logstash]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-ml]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-monitoring]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-rollup]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-security]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-sql]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-upgrade]
mm-elastic  | [2023-01-21T10:45:03,936][INFO ][o.e.p.PluginsService     ] [JplwvI5] loaded module [x-pack-watcher]
mm-elastic  | [2023-01-21T10:45:03,937][INFO ][o.e.p.PluginsService     ] [JplwvI5] no plugins loaded
mm-elastic  | [2023-01-21T10:45:05,148][INFO ][o.e.x.m.p.l.CppLogMessageHandler] [JplwvI5] [controller/108] [Main.cc@114] controller (64 bit): Version 6.8.12 (Build 39bf066b214253) Copyright (c) 2020 Elasticsearch BV
mm-elastic  | [2023-01-21T10:45:05,373][INFO ][o.e.d.DiscoveryModule    ] [JplwvI5] using discovery type [zen] and host providers [settings]
mm-elastic  | [2023-01-21T10:45:05,662][INFO ][o.e.n.Node               ] [JplwvI5] initialized
mm-elastic  | [2023-01-21T10:45:05,662][INFO ][o.e.n.Node               ] [JplwvI5] starting ...
mm-elastic  | [2023-01-21T10:45:05,737][INFO ][o.e.t.TransportService   ] [JplwvI5] publish_address {172.21.0.3:9300}, bound_addresses {0.0.0.0:9300}
mm-elastic  | [2023-01-21T10:45:05,743][INFO ][o.e.b.BootstrapChecks    ] [JplwvI5] bound or publishing to a non-loopback address, enforcing bootstrap checks
mm-elastic  | ERROR: [1] bootstrap checks failed
mm-elastic  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
mm-elastic  | [2023-01-21T10:45:05,746][INFO ][o.e.n.Node               ] [JplwvI5] stopping ...
mm-elastic  | [2023-01-21T10:45:05,754][INFO ][o.e.n.Node               ] [JplwvI5] stopped
mm-elastic  | [2023-01-21T10:45:05,754][INFO ][o.e.n.Node               ] [JplwvI5] closing ...
mm-elastic  | [2023-01-21T10:45:05,759][INFO ][o.e.n.Node               ] [JplwvI5] closed
mm-elastic  | [2023-01-21T10:45:05,760][INFO ][o.e.x.m.p.NativeController] [JplwvI5] Native controller process has stopped - no new native processes can be started
mm-elastic exited with code 78
```

which can be resolved by increasing max virtual memory
```
sudo sysctl -w vm.max_map_count=262144
```
though this requires sudo and `/etc/sysctl.conf` needs to be modified for permanent effect.
