### ISSUE TITLE
demo: pip install -r requirements.txt dies with SyntaxError

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#6]
Step `pip install -r requirements.txt` dies with this (probably python-package version mismatch):
 
Collecting dm.xmlsec.binding==1.3.2 (from python-saml==2.1.5->-r requirements.txt (line 46))
  Downloading https://files.pythonhosted.org/packages/0c/47/c8e17a5fec7bc86b092ba6841c2db7ce5e828327eb72d6a8c4c93a19f62e/dm.xmlsec.binding-1.3.2.tar.gz (119kB)
    100% |████████████████████████████████| 122kB 10.7MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/4z/6tmqh9hx68v3081lpb6j33k00000gs/T/pip-install-pmczeksh/dm.xmlsec.binding/setup.py", line 72
        print "Warning : cflag %s skipped" % flag
                                         ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/4z/6tmqh9hx68v3081lpb6j33k00000gs/T/pip-install-pmczeksh/dm.xmlsec.binding/

aliasing python to python2.7 inside the VE does not help.
commenting out saml package in requirements/.txt lets it finish with no other issues

**Comment by cegg** [comment]
I found the solution: since aliasing python for some reason did not help, I ran it explicitely with python2.7:
`$ python2.7 -m pip install -r requirements.txt`
