### ISSUE TITLE
demo: "python pymm_run.py restore" step fails with ImportError: No module named ext.pymongo

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#7]
After installing requirements (with saml2 package commented out, see issue 6) I tried "restore" step:

```
matchminer-api$ python --version
Python 2.7.15
matchminer-api$ python pymm_run.py restore
Traceback (most recent call last):
  File "pymm_run.py", line 7, in <module>
    from matchminer import managment
  File "/Users/ipozdnya/matchminer-api/matchminer/managment.py", line 10, in <module>
    from matchminer import events
  File "/Users/ipozdnya/matchminer-api/matchminer/events.py", line 12, in <module>
    from matchminer.hooks import UtilHooks
  File "/Users/ipozdnya/matchminer-api/matchminer/hooks/__init__.py", line 1, in <module>
    from matchminer.database import get_db
  File "/Users/ipozdnya/matchminer-api/matchminer/database.py", line 2, in <module>
    from flask.ext.pymongo import MongoClient
ImportError: No module named ext.pymongo
```

I double-checked flask_pymongo, seems to be in place:
```
matchminer-api$ pip2.7 install flask_pymongo
Collecting flask_pymongo
  Downloading https://files.pythonhosted.org/packages/d5/c8/22ddacfe05893884dceef5b9ecfa683f947ba155bd63cd9d841aea29b7b7/Flask_PyMongo-2.2.0-py2.py3-none-any.whl
Requirement already satisfied: Flask>=0.11 in /usr/local/lib/python2.7/site-packages (from flask_pymongo) (1.0.2)
Requirement already satisfied: PyMongo>=3.0 in /usr/local/lib/python2.7/site-packages (from flask_pymongo) (3.7.2)
```
Please advise.. Thanks

**Comment by ethansiegl** [comment]
have you run `pip install -r requirements.txt`?

**Comment by ethansiegl** [comment]
not sure what's going wrong here. my only suggestion would be to create a new virtualenv and try to reinstall the packages ex:

```
virtualenv ~/some/dir/mm_api
. ~/some/dir/mm_api/bin/activate
pip install -r requirements.txt
python pymm_run.py serve --no-auth
```

**Comment by ethansiegl** [comment]
issue is a duplicate...closing.
