### ISSUE TITLE
demo: step "nosetests tests" gives errors: syntax, non-existing attribute and non-existent module 'rfc822' and 'engine'

### ISSUE THREAD

**Issue by cegg** [dfci/matchminer-api#8]
matchminer-api$ nosetests tests

EEEEEE....E
======================================================================
ERROR: Failure: AttributeError (module 'sys' has no attribute 'maxint')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/unit/test_api/test_neg_genomic.py", line 5, in <module>
    from matchminer.database import get_db
  File "/Users/ipozdnya/matchminer-api/matchminer/database.py", line 4, in <module>
    from matchminer.settings import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings.py", line 56, in <module>
    from matchminer.settings_dev import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings_dev.py", line 20, in <module>
    TOKEN_TIMEOUT = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'

======================================================================
ERROR: Failure: ImportError (No module named 'rfc822')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/unit/test_api/test_response.py", line 7, in <module>
    from rfc822 import formatdate
ImportError: No module named 'rfc822'

======================================================================
ERROR: Failure: AttributeError (module 'sys' has no attribute 'maxint')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/unit/test_api/test_status.py", line 6, in <module>
    from matchminer.database import get_db
  File "/Users/ipozdnya/matchminer-api/matchminer/database.py", line 4, in <module>
    from matchminer.settings import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings.py", line 56, in <module>
    from matchminer.settings_dev import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings_dev.py", line 20, in <module>
    TOKEN_TIMEOUT = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'

======================================================================
ERROR: Failure: SyntaxError (invalid token (test_trial.py, line 621))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/unit/test_api/test_trial.py", line 621
    "site": [{"id": [01], "value": "Dana-Farber Cancer Institute"}],
                      ^
SyntaxError: invalid token

======================================================================
ERROR: Failure: AttributeError (module 'sys' has no attribute 'maxint')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/unit/test_api/test_utilities.py", line 4, in <module>
    from matchminer.database import get_db
  File "/Users/ipozdnya/matchminer-api/matchminer/database.py", line 4, in <module>
    from matchminer.settings import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings.py", line 56, in <module>
    from matchminer.settings_dev import *
  File "/Users/ipozdnya/matchminer-api/matchminer/settings_dev.py", line 20, in <module>
    TOKEN_TIMEOUT = sys.maxint
AttributeError: module 'sys' has no attribute 'maxint'

======================================================================
ERROR: Failure: ImportError (No module named 'engine')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/test_cbioengine/test_engine.py", line 4, in <module>
    from tcm import CBioEngine
  File "/Users/ipozdnya/matchminer-api/tcm/__init__.py", line 1, in <module>
    from engine import CBioEngine
ImportError: No module named 'engine'

======================================================================
ERROR: Failure: ImportError (No module named 'rfc822')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/Users/ipozdnya/ve_matchminer/lib/python3.5/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 697, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/Users/ipozdnya/matchminer-api/tests/test_matchminer/__init__.py", line 10, in <module>
    from rfc822 import formatdate
ImportError: No module named 'rfc822'

Looks like it's trying to import python3 packages for some reason even though my python is aliased to 2.7. 
When I force it to run with python2.7,  ( `python2.7 -m nose tests` ) another error happens:
```
ERROR: Failure: ImportError (No module named pytest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/numpy/1.15.4_2/libexec/nose/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/local/Cellar/numpy/1.15.4_2/libexec/nose/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/local/Cellar/numpy/1.15.4_2/libexec/nose/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/ipozdnya/Library/Python/2.7/lib/python/site-packages/tests/test_transport_http.py", line 35, in <module>
    import pytest
ImportError: No module named pytest

----------------------------------------------------------------------
Ran 28 tests in 0.963s
```

I checked for pytest:

```
$ python2.7 -m pip install pytest
Requirement already satisfied: pytest in /usr/local/lib/python2.7/site-packages (4.1.0)
```

What am I missing still?
----------------------------------------------------------------------

**Comment by cegg** [comment]
python version mismatch for the most part, closing
